### ISSUE TITLE
Update for NServiceBus 9 ?

### ISSUE THREAD

**Issue by mezzo1981** [mauroservienti/NServiceBus.Extensions.DispatchRetries#197]
We use the package and want to update to NServiceBus 9, unfortunately the version is not compatible.
Will there still be an update or has the package been discontinued?

**Comment by mauroservienti** [comment]
Thanks for raising this issue, @mezzo1981.

The package is alive and kicking. I started working on this at https://github.com/mauroservienti/NServiceBus.Extensions.DispatchRetries/pull/199; I'm having some trouble with the approval files; everything else is green.

**Comment by mezzo1981** [comment]
Great, thanks for the quick reply.
At the moment this is our blocker and we are looking forward to the new package! :-)

**Comment by mauroservienti** [comment]
The `master` branch is now using NServiceBus 9. I'll try to get the package on NuGet today.

**Comment by mauroservienti** [comment]
[3.0.1 is available on NuGet](https://www.nuget.org/packages/NServiceBus.Extensions.DispatchRetries/3.0.1) (I made a mistake while releasing 3.0.0 and had to burn a release 😬)

**Comment by mauroservienti** [comment]
Release: https://github.com/mauroservienti/NServiceBus.Extensions.DispatchRetries/releases/tag/3.0.1
