### ISSUE TITLE
Passing ResiliencePipeline when configuring DispatchRetriesConfiguration 

### ISSUE THREAD

**Issue by benitowolf** [mauroservienti/NServiceBus.Extensions.DispatchRetries#205]
Depending on the [Polly Migration Guide](https://www.pollydocs.org/migration-v8.html) the term _Policy_ is replaced by _Strategy_ / _ResiliencePipeline_. Please give an update for the methods _DefaultImmediateDispatchRetriesPolicy_() and _DefaultBatchDispatchRetriesPolicy_() to support passing a ResiliencePipeline instead of AsyncRetryPolicy. This is needed for a full migration to Polly.Core

**Comment by mauroservienti** [comment]
Thanks for raising this, @benitowolf. I'll get to it by the end of this week.

**Comment by mauroservienti** [comment]
Started working on ResiliencePipeline support in  https://github.com/mauroservienti/NServiceBus.Extensions.DispatchRetries/pull/206. It'll take a bit more time due to the ramifications of the changes, but I don't see any blockers at the moment.

**Comment by mauroservienti** [comment]
The implementation is ready in https://github.com/mauroservienti/NServiceBus.Extensions.DispatchRetries/pull/206. It'll allow the use of resilience strategies in the following manner:

```csharp
var endpointConfiguration = new EndpointConfiguration("myEndpointName");

var resiliencePipeline = new ResiliencePipelineBuilder()
    .AddRetry(new RetryStrategyOptions 
    {
        MaxRetryAttempts = 3,
        OnRetry = _ => ValueTask.CompletedTask
    })
endpointConfiguration.DispatchRetries(resiliencePipeline);
```

Similarly, for all the other retry configuration options.

@benitowolf, thoughts?

**Comment by benitowolf** [comment]
Thanks for quick response and implementing @mauroservienti!
Please let's publish this as a new release. Maybe the documentation has to be updated, too.

**Comment by mauroservienti** [comment]
The package is on [NuGet](https://www.nuget.org/packages/NServiceBus.Extensions.DispatchRetries/3.1.0) and should be available as soon as indexing is completed.
